---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: push-sbom-to-pyxis-run-empty-params
spec:
  params:
    - name: containerImageIDs
      value: ""
    - name: pyxisSecret
      value: ""
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: legacy
      - name: pathInRepo
        value: catalog/task/push-sbom-to-pyxis/0.3/push-sbom-to-pyxis.yaml
