---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: get-ocp-version-run-empty-params
spec:
  params:
    - name: fbcFragment
      value: ""
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: legacy
      - name: pathInRepo
        value: catalog/task/get-ocp-version/0.2/get-ocp-version.yaml
